name: Run prettier check

on:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
      - uses: actions/cache@v6
        name: Configure npm caching
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/prettier.yml') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Run prettier
        run: |-
          npx prettier@1.19.1 --check '_data/*/*.json'
